# Generated by Django 4.2.15 on 2024-09-03 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=50)),
                ('verify_status', models.BooleanField(null=True)),
                ('photo', models.CharField(max_length=350)),
                ('description', models.CharField(max_length=1500)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Member.roles')),
            ],
        ),
    ]
