# Generated by Django 4.2.15 on 2024-09-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0002_alter_members_description_alter_members_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='photo',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
